name: Pull Request Checker

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - update
    
  schedule:
    - cron: "0 0 * * *"  # Run the script daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Install dependencies
      run: |
        pip install pandas

    - name: Run sample.py
      run: python sample.py
