name: Pull Request Notifications

on:
  pull_request:
    types:
      - closed
      - reopened

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Debug Event Payload
        run: echo "${{ toJson(github.event) }}"
        
      - name: Execute GitHub Script
        id: check_updates
        uses: actions/github-script@v4
        with:
          script: |
            const { pull_request, repository } = context.payload;
            const action = context.payload.action;
            if (action === 'closed') {
              const notification = `
                Pull Request #${pull_request.number} in ${repository.full_name} was closed.
                Title: ${pull_request.title}
                URL: ${pull_request.html_url}
              `;
              console.log(notification);
              console.log("::set-output name=notification::" + notification);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Send Email Notification
        if: steps.check_updates.outputs.notification != ''
        run: |
          echo "${{ steps.check_updates.outputs.notification }}" | \
          sendemail -f ${{ secrets.SENDER_EMAIL }} -t ${{ secrets.RECIPIENT_EMAIL }} \
          -s ${{ secrets.SMTP_SERVER_ADDRESS }} -o tls=yes -xu ${{ secrets.SMTP_USERNAME }} -xp ${{ secrets.SMTP_PASSWORD }} -m
