name: Pull Request Notifications

on:
  issue_comment:
    types:
      - edited

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Pull Request Number
        id: pr_number
        run: echo "::set-output name=pr_number::$(echo ${{ github.event.issue.pull_request.url }} | grep -oE '[0-9]+$')"

      - name: Get Pull Request Details
        id: pr_details
        run: |
          echo "::set-output name=pr_title::$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' ${{ github.event.issue.pull_request.url }} | jq -r '.title')"
          echo "::set-output name=pr_repo::$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' ${{ github.event.issue.pull_request.url }} | jq -r '.base.repo.full_name')"
          echo "::set-output name=pr_url::$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' ${{ github.event.issue.pull_request.url }} | jq -r '.html_url')"

      - name: Debug Pull Request Details
        run: |
          echo "Pull Request Number: ${{ steps.pr_number.outputs.pr_number }}"
          echo "Pull Request Title: ${{ steps.pr_details.outputs.pr_title }}"
          echo "Pull Request Repo: ${{ steps.pr_details.outputs.pr_repo }}"
          echo "Pull Request URL: ${{ steps.pr_details.outputs.pr_url }}"

      - name: Send Email Notification
        run: |
          echo "Pull Request #${{ steps.pr_number.outputs.pr_number }} in ${{ steps.pr_details.outputs.pr_repo }} was reopened and comment was updated." \
               "Title: ${{ steps.pr_details.outputs.pr_title }}" \
               "URL: ${{ steps.pr_details.outputs.pr_url }}" | \
          sendemail -f ${{ secrets.SENDER_EMAIL }} -t ${{ secrets.RECIPIENT_EMAIL }} \
          -s ${{ secrets.SMTP_SERVER_ADDRESS }} -o tls=yes -xu ${{ secrets.SMTP_USERNAME }} -xp ${{ secrets.SMTP_PASSWORD }} -m "Subject: Pull Request Reopened and Comment Updated\n\n$(cat)"
