name: Pull Request Notifications

on:
  pull_request:
    types:
      - closed
      - reopened

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Send notification
        uses: actions/github-script@v4
        with:
          script: |
            const { issue, repository } = context.https://dcf3-223-237-232-145.ngrok.io/webhook;
            const action = context.payload.action;

            if (action === 'closed') {
              const notification = `
                Pull Request #${issue.number} in ${repository.full_name} was closed.
                Title: ${issue.title}
                URL: ${issue.html_url}
              `;

              console.log(notification);
