name: Pull Request Notifications

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_run:
    workflows:
      - "Check PR Updates"
    types:
      - requested
      - reopened
      - synchronized

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Debug Event Payload
        run: echo "${{ toJson(github.event) }}"

      - name: Execute GitHub Script
        id: check_updates
        uses: actions/github-script@v4
        with:
          script: |
            const runPayload = context.payload.workflow_run;
            if (runPayload.conclusion === 'success' && runPayload.workflow === 'Check PR Updates') {
              const pullRequests = runPayload.pull_requests;
              if (pullRequests.length > 0) {
                const pullRequest = pullRequests[0];
                const action = pullRequest.event;
                if (action === 'closed') {
                  const notification = `
                    Pull Request #${pullRequest.number} in ${pullRequest.base.repo.full_name} was closed.
                    Title: ${pullRequest.title}
                    URL: ${pullRequest.html_url}
                  `;
                  console.log(notification);
                  console.log("::set-output name=notification::" + notification);
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Email Notification
        if: steps.check_updates.outputs.notification != ''
        run: |
          echo "${{ steps.check_updates.outputs.notification }}" | \
          sendemail -f ${{ secrets.SENDER_EMAIL }} -t ${{ secrets.RECIPIENT_EMAIL }} \
          -s ${{ secrets.SMTP_SERVER_ADDRESS }} -o tls=yes -xu ${{ secrets.SMTP_USERNAME }} -xp ${{ secrets.SMTP_PASSWORD }} -m "Subject: Pull Request Closed\n\n$(cat)"
