name: Pull Request Notifications

on:
  pull_request:
    types:
      - closed
      - reopened

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Send notification
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { payload, repo, issue } = context;
            const action = payload.action;

            if (action === 'closed') {
              const notification = `
                Pull Request #${issue.number} in ${repo.full_name} was closed.
                Title: ${issue.title}
                URL: ${issue.html_url}
              `;

              console.log(notification);
            } else if (action === 'reopened') {
              const notification = `
                Pull Request #${issue.number} in ${repo.full_name} was reopened.
                Title: ${issue.title}
                URL: ${issue.html_url}
              `;

              console.log(notification);
            }
