name: Pull Request Notifications

on:
  pull_request:
    types:
      - closed
      - reopened

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Debug Event Payload
        run: echo "${{ toJson(github.event) }}"

      - name: Send Payload to Server
        run: |
          PAYLOAD_URL=" https://bb3b-136-226-245-14.ngrok.io/webhook"  # Replace with your server's actual endpoint
          PAYLOAD="${{ toJson(github.event) }}"
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$PAYLOAD_URL"

