name: Reopened PR Notification

on:
  pull_request:
    types:
      - reopened

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check PR Status
        id: check_pr
        run: echo ::set-output name=reopened::${{ github.event.action == 'reopened' }}

      - name: Trigger Email
        if: steps.check_pr.outputs.reopened == 'true'
        run: |
          EMAIL_API_URL="https://api.outlook.com/send-email" # Replace with your API endpoint
          EMAIL_PAYLOAD="{\"to\": \"c.bhavya@sonata-software.com\", \"subject\": \"PR Reopened\", \"message\": \"The pull request was reopened: ${{ github.event.pull_request.html_url }}\"}"

          # Send the email payload using curl
          curl -X POST -H "Content-Type: application/json" -d "$EMAIL_PAYLOAD" "$EMAIL_API_URL"